# yaml-language-server: $schema=https://raw.githubusercontent.com/nathanclevenger/dbht/main/schema.json?token=GHSAT0AAAAAABWQC5H2ZA62K7HGFSYBKBU6Y2BPMKA

name: blog
host: db.blogs.sh

Blog:
  _id: name
  name: string
  image: image
  description: markdown
  tags: Tag.blogs
  url: url

Post: 
  _id: slugify(title)
  title: string
  subtitle: string
  image: image
  content: markdown
  tags: Tag.posts

Author:
  _id: slugify(name)
  name: string
  bio: markdown
  blogs: Blog.author

Tag:
  _id: slugify(name)
  name: string
  blogs: Blog.tags
  posts: Post.tags
