
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - run: 'yarn'
      - run: 'yarn generate-schema'
      - name: Commit any changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Data updated"
          push_options: --force
